/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module sky130_sram_256B_1rw_32x64(vccd1, vssd1, clk0, csb0, web0, wmask0, spare_wen0, addr0, din0, dout0);
  input [5:0] addr0;
  wire [5:0] addr0;
  input clk0;
  wire clk0;
  input csb0;
  wire csb0;
  input [32:0] din0;
  wire [32:0] din0;
  output [32:0] dout0;
  wire [32:0] dout0;
  input spare_wen0;
  wire spare_wen0;
  input vccd1;
  wire vccd1;
  input vssd1;
  wire vssd1;
  input web0;
  wire web0;
  input [3:0] wmask0;
  wire [3:0] wmask0;
endmodule
