// Auto-generated by OpenLane
module tt_um_openram_top(
`ifdef USE_POWER_PINS
  input VPWR,
  input VGND,
`endif
  input[7:0] ui_in,
  output[7:0] uo_out,
  input[7:0] uio_in,
  output[7:0] uio_out,
  output[7:0] uio_oe,
  input ena,
  input clk,
  input rst_n
);
endmodule
